### ISSUE TITLE
Have queue.onEmpty() instantly resolve when queue.size === 0

### ISSUE THREAD

**Issue by edorivai** [sindresorhus/p-queue#12]
I'm currently using the following pattern to simulate said behavior:

```js
if (queue.size > 0) await queue.onEmpty();
doSomethingAfterQueueIsFinished();
```

Which could be simplified to

```js
await queue.onEmpty();
doSomethingAfterQueueIsFinished();
```

if `queue.onEmpty()` would return a resolved promise when `queue.size === 0`. Currently, the promise from `onEmpty` will never resolve, unless another item is added to the queue, and finishes.

Would love to know other peeps' thoughts.

**Comment by AlexTes** [comment]
@edorivai sup buuuuudy 😄  (<- v. good friend)

@sindresorhus _if_ you like the idea and you nudge this guy the right way, I'm sure said guy will be happy to put in the PR himself 👈 😛 .

Unwarranted commentary: I like the suggestion. onEmpty seems to be a sort of hook to do things when the queue is empty. Resolving when the queue is empty in that regard makes sense to me. But.. it complicates other scenarios 😅 .

1. Define post-queue work on empty, queue work
I'd call this the correct and probably the main use-case. In this case, the above shouldn't be an issue if I understand things correctly.

2. Queue work, define post-queue work on empty
Less correct but nonetheless understandable. Works if the work finishes after the post-queue work is defined. Breaks otherwise.

3. Define post-queue work on empty. No queue work?
Is this the use-case we're discussing? If so, maybe you can clarify why this can make sense?

In any case, my two cents is that whatever the outcome, 1. shouldn't get more complicated. It's how I expect people to use p-queue but then what do I know. Feel free to ignore my opinion on this 😁 .

You two have fun 👬 .

**Comment by edorivai** [comment]
Good points, I'll explain my use case.

I have an async cursor of which I cannot know ahead of time when it will be depleted:

```js

const queue = new PQueue({ concurrency: 20 });
const cursor = getSomeAsyncCursor();

const processItem = async() => {
  const item = await cursor.next();
  if (!item) {
    // Ah! My cursor is depleted
    if (queue.size > 0) await queue.onEmpty(); // This is where this issue comes in
    cleanUpAfterMyself();
    return;
  }
  
  // Recursively queue the next item
  queue.add(processOne);
  
  // Actually do something with my item
  await processItem(item);
};
```

In my case, I have a clear moment where I know that I won't add more items to the queue; if the cursor stops returning new items. At this time, I want to run a cleanup function, but only *after* the entire queue has been processed.

I guess I could schedule the post-queue work before adding the items (your first scenario). The problem here is that strictly speaking, we cannot be sure that the queue doesn't run empty somewhere along the process. Imagine that once, `cursor.next()` takes super long. During the wait on `cursor.next()`, the queue could complete, resulting in me running the cleanup while the cursor is still going. If I want to guarantee that the cleanup only runs *after* all cursor items have been processed, I can only attach the `onEmpty` stuff *after* the final item has been added to the queue.

This means that at the moment that I'm attaching to `onEmpty` there are two scenarios;

1. Items are still being processed (`queue.size > 0`), `onEmpty` will return a promise which will resolve in the future
2. The queue is already empty (`queue.size === 0`), `onEmpty` will return a promise which will never resolve

I understand that my proposal will break your scenario 1, this is probably not ideal.

Thoughts?

**Comment by edorivai** [comment]
Oh, and yes. In case we want to add this, I would gladly implement this and submit a PR.

**Comment by FelikZ** [comment]
I think there should be an 'event' that queue is empty, which will trigger always - no need to ask for promise every other time.

**Comment by edorivai** [comment]
But I cannot `await` an event :stuck_out_tongue:

**Comment by floatdrop** [comment]
I think this should be default behaviour for `onEmpty`, at least I would expect to get resolved promise on empty queue. 

@sindresorhus what do you think?

**Comment by edorivai** [comment]
Side note; I heard @sindresorhus will be focussing on Swift for a while :see_no_evil:

**Comment by floatdrop** [comment]
@edorivai yep. Meanwhile care to send a PR for this issue?

**Comment by sindresorhus** [comment]
> @sindresorhus what do you think?

👍 

> P.s. This indeed will break use case 1, so, perhaps, major release will be issued.

Yes, major release.
