### ISSUE TITLE
Module not found: Error: Can't resolve 'p-queue' after updating to 7.1.0

### ISSUE THREAD

**Issue by rakhadkz** [sindresorhus/p-queue#145]
6.6.2 => 7.1.0
I've found a pretty similar issue title before, but that one was related to react-scripts start command
It works with the previous Major version. I moved to ESM (replaced requied() to import). Any ideas?

node version 14.x
p-queue 7.1.0

using webpack-dev-server (^3.11.1)

**Comment by sindresorhus** [comment]
This is not the place to ask for support regarding Webpack or webpack-dev-server. This package works fine with plain Node.js. I would open an issue on Webpack or webpack-dev-server asking for help there.

**Comment by CristoMonte** [comment]
I have the same problem with parcel on version 7.1.0, but it works fine with version 6.6.2.

**Comment by sanwar-oc** [comment]
I also have the same problem with 7.1.0 with webpack build. I'm downgrading to 6.6.2.

**Comment by bjornlll** [comment]
I had the same issue with an `expo init`-generated React Native app (using Facebook's [Metro Bundler](https://facebook.github.io/metro/), not webpack).

Thanks for the tip @sanwar-oc ! Downgrading to 6.6.2 solved it for me.

**Comment by skjnldsv** [comment]
@sindresorhus this is an issue with this lib.
Importing with `import PQueue from 'p-queue'` just fails. Webpack cannot find your export path (latest webpack5, using tons of other esm import and they all work fine)

**Comment by JamesGarbaczewski** [comment]
Ran into the same issue.  Importing
`import PQueue from 'p-queue/dist';`
worked

**Comment by tlgimenes** [comment]
I'm having the same problem in here and I think this isn't a problem with this library. I think, however, for compatibility reasons, a "module" field is missing on this lib's package.json so tools like tsdx (that uses rollup) can work fine.

**Comment by okbeng03** [comment]
> Ran into the same issue. Importing
> `import PQueue from 'p-queue/dist';`
> worked

The error maybe [package not export main entry point](https://nodejs.org/dist/latest-v14.x/docs/api/packages.html#packages_main_entry_point_export)

I'm try local, add the `main define` , it works

**Comment by kitsunde** [comment]
It indeed runs just fine with plain javascript.

Another issue is that it confuses [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unresolved.md) on `import/no-unresolved`. Targeting `/dist` silences it.

```js
import PQueue from 'p-queue/dist';
```

This isn't the case with `p-all`, `p-map`, or `p-throttle`, not sure what's different in this module, but my project is only partially `esm` and it's only maintained for pure `esm` projects.

**Comment by mifi** [comment]
Doing some research, it seems that `p-queue` is different from Sindre's other modules in that `p-queue` has a build step and exports `./dist/index.js`:

https://github.com/sindresorhus/p-queue/blob/c12ec2e10c99698862b6d03ce28bc54e4bb02fdc/package.json#L9

Meanwhile the other packages don't have a build step but instead `"exports": "./index.js",` directly:
- https://github.com/sindresorhus/p-throttle/blob/035a2c2d9f1def7dbbee90939f56a3256f7c5f5d/package.json#L14
- https://github.com/sindresorhus/p-series/blob/212bcf2a0712af8451f90c72f2b2b8006b1c7f60/package.json#L14
- https://github.com/sindresorhus/p-all/blob/cdfa57c7df33a6b097568de091ce57edffad43fd/package.json#L14
- https://github.com/sindresorhus/p-map/blob/66b039b20d362c3d508f15b11dd867638b02f75b/package.json#L14

I'm guessing that webpack and other bundlers, when they don't find a `main` field, they will fallback to using the default `index.js`, ([see specification here](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#main)). For all the other packages, this is fine because the file is indeed stored at `./index.js`, however for `p-queue`, the file is stored in `./dist/index.js`. Not sure why webpack (and other bundlers) are ignoring the `exports` directive though. Could be a bug or ambiguity in the specifications.

**Comment by kolyasya** [comment]
`import PQueue from 'p-queue/dist';` worked for me in Meteor app.

This should be documented somehow 🤔

**Comment by joao-sd** [comment]
After wasting hours of my life looking for a solution to this, the only thing that comes to my mind is:
```
Why the hell JS/TS cannot simply WORK?
```

**Comment by lightrow** [comment]
`import PQueue from 'p-queue/dist'` no longer works when moduleResolution is set to NodeNext with react native 0.74
