### ISSUE TITLE
Change output target to ES5 please

### ISSUE THREAD

**Issue by Silviu-Marian** [sindresorhus/p-queue#83]
Hi there.

We need broader compatibility with older browsers. The current output target produces spread/rest operators and they can't be interpreted by older engines.

Just a matter of changing https://github.com/sindresorhus/p-queue/blob/master/tsconfig.json#L5 and republishing.

```
		"target": "es5",
```

**Comment by sindresorhus** [comment]
Sorry, it's up to you to transpile it with Babel if you want to use it in older browsers. I don't want to punish Node.js and newer browser with code bloat just because of older browsers.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
